### ISSUE TITLE
More errors to constants.

### ISSUE THREAD

**Issue by pavlovskyive** [annavasylashko/euro-diffusion#1]
https://github.com/annavasylashko/euro-diffusion/blob/58cedf255cba6772af7d276b24507179627c68d1/src/FileReader.js#L40

Error messages are better be in one place + be constant values to avoid "magic strings" in code.

**Comment by annavasylashko** [comment]
fixed in https://github.com/annavasylashko/euro-diffusion/commit/b2c5acbe150c90ca367cc200eeb379c5a71a5753
