### ISSUE TITLE
Move method to separate utility function.

### ISSUE THREAD

**Issue by pavlovskyive** [annavasylashko/euro-diffusion#2]
https://github.com/annavasylashko/euro-diffusion/blob/58cedf255cba6772af7d276b24507179627c68d1/src/entities/MapGrid.js#L156

This functionality is not suited to be a class method.

**Comment by annavasylashko** [comment]
fixed in https://github.com/annavasylashko/euro-diffusion/commit/f20fd4a8d6745ad519c894dcf7247127195b5c8a
